# Contribution Snake
name: generate animation

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"

  # To run it the Amanually
  workflow_dispatch:

  # Run on every push on main branch
  push:
    branches: 
    - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            ddist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#fc7905&color_dots=#ffffff,#a051ff,#7c49eb,#6d41cc,#44287f
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fc7905&color_dots=#0d1117,#a051ff,#7c49eb,#6d41cc,#44287f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
